---
version: "2.1"
volumes:
    portainer_data: {}
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 8000:8000
      - 9443:9443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  bazarr:
    container_name: bazarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: lscr.io/linuxserver/bazarr:latest
    volumes:
      - $DOCKERDIR/bazarr:/config
      - $MOVIESDIR:/movies #optional
      - $SERIESDIR:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
  jellyfin:
    container_name: jellyfin
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - JELLYFIN_PublishedServerUrl=$SERVER_IP #optional
    group_add:
      - "109" # Change this to match your "render" host group id and remove this comment
    image: lscr.io/linuxserver/jellyfin:latest
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/jellyfin:/config
      - $SERIESDIR:/data/tvshows
      - $MOVIESDIR:/data/movies
  lidarr:
    container_name: lidarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: lscr.io/linuxserver/lidarr:latest
    ports:
      - 8686:8686
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/lidarr:/config
      - $MUSICDIR:/music #optional
      - $DOWNLOADSDIR:/downloads #optional
  prowlarr:
    container_name: prowlarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - 9696:9696
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/prowlarr:/config
  radarr:
    container_name: radarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - 7878:7878
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/radarr:/config
      - $MOVIESDIR:/movies #optional
      - $DOWNLOADSDIR:/downloads #optional
  readarr:
    container_name: readarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: lscr.io/linuxserver/readarr:develop
    ports:
      - 8787:8787
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/readarr:/config
      - $BOOKSDIR:/books #optional
      - $DOWNLOADSDIR:/downloads #optional
  sonarr:
    container_name: sonarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - 8989:8989
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/sonarr:/config
      - $SERIESDIR:/tv #optional
      - $DOWNLOADSDIR:/downloads #optional
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    ports:
      - 80:7575
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/homarr:/app/data/configs
      - $DOCKERDIR/homarr/data:/data
      - $DOCKERDIR/homarr/icons:/app/public/icons
  qbittorrent:
    cap_add:
      - NET_ADMIN
    container_name: qbittorrentvpn
    image: binhex/arch-qbittorrentvpn
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
      - VPN_ENABLED=yes
      - WEBUI_PORT=8080
      - LAN_NETWORK=192.168.0.0/24
      - ENABLE_PRIVOXY=yes
      - VPN_PROV=custom
      - VPN_CLIENT=wireguard
    ports:
      - 8080:8080
      - 8118:8118
      - 6881:6881
      - 6881:6881/udp
    privileged: true
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/qbittorrent:/config
      - $DOWNLOADSDIR:/data
      - /etc/localtime:/etc/localtime:ro
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
  jellyseerr:
     container_name: jellyseerr
     environment:
      - LOG_LEVEL=debug
      - TZ=$TZ
     image: fallenbagel/jellyseerr:latest
     ports:
      - 5055:5055
     restart: unless-stopped
     volumes:
      - $DOCKERDIR/jellyseer:/app/config
  timetagger:
    container_name: timetagger
    image: ghcr.io/almarklein/timetagger
    ports:
      - "5555:80"
    volumes:
      - $DOCKERDIR/timetagger:/root/_timetagger
    environment:
      - TIMETAGGER_BIND=0.0.0.0:80
      - TIMETAGGER_DATADIR=/root/_timetagger
      - TIMETAGGER_LOG_LEVEL=info
      - TIMETAGGER_CREDENTIALS=$TIMETAGGER_CREDENTIALS
  kavita:
    container_name: kavita
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: lscr.io/linuxserver/kavita:latest
    ports:
      - 5000:5000
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/kavita:/config
      - $BOOKSDIR:/data