---
version: "2.1"
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/homarr:/app/data/configs
      - $DOCKERDIR/homarr/icons:/app/public/icons
    ports:
      - 7575:7575