---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/radarr:/config
      - $MOVIESDIR:/movies #optional
      - $DOWNLOADSDIR:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped