version: "2.1"
services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    ports:
      - 80:7575
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/homarr:/app/data/configs
      - $DOCKERDIR/homarr/data:/data
      - $DOCKERDIR/homarr/icons:/app/public/icons
