version: "2.1"
services:
  jellyfin:
    container_name: jellyfin
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - JELLYFIN_PublishedServerUrl=$SERVER_IP #optional
    group_add:
      - "109" # Change this to match your "render" host group id and remove this comment
    image: lscr.io/linuxserver/jellyfin:latest
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/jellyfin:/config
      - $SERIESDIR:/data/tvshows
      - $MOVIESDIR:/data/movies
