version: "2.1"
services:
  lidarr:
    container_name: lidarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: lscr.io/linuxserver/lidarr:latest
    ports:
      - 8686:8686
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/lidarr:/config
      - $MUSICDIR:/music #optional
      - $DOWNLOADSDIR:/downloads #optional
