version: "2.1"
services:
  prowlarr:
    container_name: prowlarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - 9696:9696
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/prowlarr:/config
