version: "2.1"
services:
  qbittorrent:
    cap_add:
      - NET_ADMIN
    container_name: qbittorrentvpn
    image: binhex/arch-qbittorrentvpn
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
      - VPN_ENABLED=yes
      - WEBUI_PORT=8080
      - LAN_NETWORK=192.168.0.0/24
      - ENABLE_PRIVOXY=yes
      - VPN_PROV=custom
      - VPN_CLIENT=wireguard
    ports:
      - 8080:8080
      - 8118:8118
      - 6881:6881
      - 6881:6881/udp
    privileged: true
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/qbittorrent:/config
      - $DOWNLOADSDIR:/data
      - /etc/localtime:/etc/localtime:ro
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
