version: "2.1"
services:
  readarr:
    container_name: readarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: lscr.io/linuxserver/readarr:develop
    ports:
      - 8787:8787
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/readarr:/config
      - $BOOKSDIR:/books #optional
      - $DOWNLOADSDIR:/downloads #optional
