version: "2.1"
services:
  sonarr:
    container_name: sonarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - 8989:8989
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/sonarr:/config
      - $SERIESDIR:/tv #optional
      - $DOWNLOADSDIR:/downloads #optional
