version: "2.1"
services:
  bazarr:
    container_name: bazarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: lscr.io/linuxserver/bazarr:latest
    volumes:
      - $DOCKERDIR/bazarr:/config
      - $MOVIESDIR:/movies #optional
      - $SERIESDIR:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
